---
- name: Set system repos
  tags: apt_init,apt_set_system_repos
  when: apt_system_repos is defined and apt_system_repos | length > 0
  ansible.builtin.template:
    dest: "/etc/apt/sources.list"
    src: "{{ common_etc_templates_path }}/apt_sources.list.j2"
    mode: "0644"
  loop: "{{ apt_system_repos }}"
  loop_control:
    loop_var: arl

- name: Update packages cache
  tags: apt_init,apt_update_cache,apt_set_system_repos
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system
  when: apt_upgrade_force is defined and apt_upgrade_force | bool
  tags: apt_init,apt_upgrade_system
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true

- name: Install system packages
  tags: apt_init,system_install
  ansible.builtin.apt:
    name: "{{ apt_system_packages }}"

- name: Set python3 default interpreter
  tags: set_python
  community.general.alternatives:
    name: "python"
    link: "/usr/bin/python"
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
    state: "{{ item.state }}"
  loop: "{{ apt_python }}"

- name: Setup any repos
  ansible.builtin.include_tasks: "apt-repo-add.yml"
