---
- name: Add apt repos
  when: apt_repo_list is defined and apt_repo_list | length > 0
  block:
    - name: Add repos gpg key
      become: true
      become_user: root
      when: item.gpg_key is defined and item.gpg_key | length > 0
      tags: apt_init,apt_add_repo
      ansible.builtin.apt_key:
        url: "{{ item.gpg_key }}"
        state: present
        keyring: "{{ item.gpg_keyring | default(omit) }}"
      loop: "{{ apt_repo_list }}"
    - name: Add repos for apt
      become: true
      become_user: root
      tags: apt_init,apt_add_repo
      ansible.builtin.template:
        dest: "/etc/apt/sources.list.d/{{ arl.filename }}.list"
        mode: "0644"
        src: "{{ common_templates_path }}/apt_sources.list.j2"
      loop: "{{ apt_repo_list }}"
      loop_control:
        loop_var: arl
    - name: Update packages cache
      become: true
      become_user: root
      tags: apt_init,apt_update_cache,apt_add_repo
      ansible.builtin.apt:
        update_cache: true
