---
- name: Check requirements
  ansible.builtin.import_tasks: "prereqs.yml"

- name: Set system-independ variables
  ansible.builtin.include_vars:
    file: "{{ common_vars_dir }}/main.yml"
  tags: system_config,system_init,system_install,system_pm_init,common_world_install

- name: Set system-depend variables
  ansible.builtin.include_vars:
    file: "{{ common_vars_dir }}/{{ ansible_os_family }}.yml"
  tags: system_config,system_init,system_install,system_pm_init,common_world_install

- name: Create any config dirs
  ansible.builtin.file:
    path: "{{ item.name }}"
    state: directory
    mode: "{{ item.mode }}"
  loop: "{{ common_config_dirs | default({}) }}"
  tags: system_init,system_config,system_config_dirs

- name: Create ops user
  tags: system_init,sys_ops_user
  when: common_ops_user is defined and common_ops_user | length > 0
  block:
    - name: Create sudo and primary group
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
      loop: "{{ common_sudo_groups }}"
    - name: Create user
      ansible.builtin.user:
        append: true
        create_home: true
        groups:
          - "{{ common_sudo_group }}"
        name: "{{ common_ops_user }}"
        uid: "{{ common_ops_uid }}"
      tags: system_init,sys_ops_user
    - name: Get id_rsa.pub into variable
      ansible.builtin.set_fact:
        local_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      tags: system_init,sys_ops_user
    - name: Add id_rsa.pub into ops user authorized_keys
      ansible.posix.authorized_key:
        user: "{{ common_ops_user }}"
        key: "{{ local_pub_key }}"
      tags: system_init,sys_ops_user
    - name: Check if sudoers directory exists
      ansible.builtin.file:
        path: "{{ common_sudoers_dir }}"
        state: directory
        mode: "0750"
      tags: system_init,sys_ops_user
    - name: Add ops user into sudoers
      community.general.sudoers:
        commands: ALL
        group: "{{ common_sudo_group }}"
        host: "ALL"
        name: "ops_user_sudo"
        nopassword: true

- name: Configure common network parameters
  ansible.builtin.import_tasks: "network.yml"
  tags: system_init,network_config

### BEGIN: Setup package manager ###
- name: Init of package management system
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}-init.yml"
  tags: system_init,system_pm_init
### END: Setup package manager ###

### BEGIN: Edit any system configs ###
- name: Edit any system config
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    create: "{{ item.create | default(true) }}"
    mode: "{{ item.file_mode | default('0644') }}"
  loop: "{{ common_system_config | default({}) }}"
  tags: system_init,system_config
### END: Edit any system configs ###

### BEGIN: Locale settings ###
- name: Create /etc/locale.gen
  ansible.builtin.template:
    src: "{{ common_etc_templates_path }}/locale.gen.j2"
    dest: "/etc/locale.gen"
    mode: "0644"
  notify: Rebuild locales
  when: ansible_os_family == "Gentoo" or ansible_os_family == "Debian"
  tags: system_init,locale_init
- name: Create /etc/locale.conf
  ansible.builtin.template:
    src: "{{ common_etc_templates_path }}/locale.conf.j2"
    dest: "{{ lc.config_path }}"
    mode: "0644"
  loop: "{{ common_lang_settings }}"
  loop_control:
    loop_var: lc
  tags: system_init,locale_init
- name: Create /etc/vconsole.conf
  ansible.builtin.template:
    src: "{{ common_etc_templates_path }}/vconsole.conf.j2"
    dest: "/etc/vconsole.conf"
    mode: "0644"
  when: common_kbd_n_cfont_settings is defined and common_kbd_n_cfont_settings | length > 0
  tags: system_init,locale_init
### END: Locale settings ###

### BEGIN: Set system date and time and time sync ###
- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  tags: system_init,timesync_init
# Time sync is not need on containers
- name: Set time sync if needed
  when: common_timesync_service != 'none'
  block:
    - name: Install timesync packages on normal Linux distros
      when: ansible_pkg_mgr != "apt_rpm"
      ansible.builtin.package:
        name: "{{ item }}"
        state: "present"
      loop: "{{ common_timesync_packages | default([]) }}"
    - name: Install timesync packages on Alt Linux
      when: ansible_pkg_mgr == "apt_rpm"
      community.general.apt_rpm:
        name: "{{ item }}"
        state: "present_not_latest"
      loop: "{{ common_timesync_packages | default([]) }}"
    - name: Set timesync config file header
      ansible.builtin.blockinfile:
        path: "{{ common_time_config_path }}"
        insertbefore: "BOF"
        create: true
        mode: "0644"
        block: |
          # File "{{ common_time_config_path }}"
          # managed by ansible. You shouldn't edit it manually
      tags: system_init,timesync_init
    - name: Edit time sync config
      ansible.builtin.lineinfile:
        path: "{{ common_time_config_path }}"
        state: present
        regexp: '^\s*#?\s*{{ item.name }}\s*=.*'
        line: "{{ item.name }}{% if common_timesync_service == 'systemd-timesyncd' %}={% else %} {% endif %}{{ item.value }}"
        create: true
        mode: "0644"
      loop: "{{ common_timesync_params }}"
      notify:
        - Timesync_service enable
        - Timesync_service restart
      tags: system_init,timesync_init
### END: Set system date and time and time sync ###

### BEGIN: Install system ###
- name: Install all packages
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: common_world_install,common_install
### END: Install system ###

### BEGIN: Add systemd units ###
- name: Add selfmade systemd units
  when: ansible_service_mgr == 'systemd' and common_systemd_units is defined and common_systemd_units | length > 0
  tags: system_init,systemd_units
  block:
    - name: Add systemd unit files into system
      ansible.builtin.template:
        src: "{{ srvc.template_path }}/{{ srvc.template_name | default('systemd_unit') }}.{{ srvc.task | default('service') }}.j2"
        dest: "/etc/systemd/system/{{ srvc.unit_name }}{% if srvc.instances is defined %}@{% endif %}.{{ srvc.task | default('service') }}"
        mode: "0644"
      loop: "{{ common_systemd_units }}"
      loop_control:
        loop_var: srvc
      notify: Systemd daemon reload
      tags: system_init,systemd_units
    - name: Add simple selfmade system units into boot process
      ansible.builtin.systemd_service:
        name: "{{ item.unit_name }}"
        enabled: true
      when: item.instances is not defined or item.instances | length == 0
      loop: "{{ common_systemd_units }}"
    - name: Add instantiated selfmade system units into boot process
      ansible.builtin.systemd_service:
        name: "{{ item.0.unit_name }}@{{ item.1 }}"
        enabled: true
      when: item.0.instances is defined and item.0.instances | length > 0
      loop: "{{ common_systemd_units | subelements('instances') }}"
### END: Add systemd units ###

### BEGIN: Setup crontab ###
- name: Add crontabs
  ansible.builtin.cron:
    backup: "{{ item.backup | default(omit) }}"
    cron_file: "{{ item.user }}"
    day: "{{ item.day | default('*') }}"
    disabled: "{{ item.disabled | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    hour: "{{ item.hour | default('*') }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    month: "{{ item.month | default('*') }}"
    name: "{{ item.name }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user }}"
    weekday: "{{ item.weekday | default('*') }}"
  loop: "{{ common_crontabs }}"
  tags: system_init,crontab
### END: Setup crontab ###

### BEGIN: Set polisies by edit polkit rules ###
- name: Clean polkit rules directory
  when: clean_polkit_rules_dir_force is defined and clean_polkit_rules_dir_force | bool
  tags: system_init,polkit_rules_set
  block:
    - name: Get list of files in /etc/polkit-1/rules.d/
      ansible.builtin.find:
        paths: "/etc/polkit-1/rules.d/"
        patterns: '*.rules'
      register: files2del
    - name: Delete files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files2del.files }}"
- name: Copy polkit rules
  tags: system_init,polkit_rules_set
  ansible.builtin.template:
    src: "{{ item.template_path }}/{{ item.action }}.rules.j2"
    dest: "/etc/polkit-1/rules.d/{{ item.action }}.rules"
    mode: "0644"
  loop: "{{ common_polkit_rules | default({}) }}"
### END: Set polisies by edit polkit rules ###

### BEGIN: ###
- name: Manage own SSL keys
  ansible.builtin.include_tasks: "ssl_keys.yml"
  tags: system_init,ssl_keys
  loop: "{{ common_ssl_keys | default([]) }}"
  loop_control:
    loop_var: csk
### END: ###
