---

- name: get current profile
  ansible.builtin.shell: eselect profile list | grep \* | sed -e 's/\]\|\[\|\*\|([^)]*)\|^\s*//g'
  register: current_profile
  ignore_errors: true
  check_mode: no
  tags: portage_set_profile

- name: set profile
  ansible.builtin.shell: "eselect profile set {{ portage_profile }}"
  when: portage_profile not in current_profile.stdout
  tags: portage_set_profile

- name: check if config directories exist
  ansible.builtin.file:
    path: "/etc/portage/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop: "{{ portage_etc_dirs }}"
  tags: portage_init

- name: copy config templates into /etc/portage
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/portage/{{ item.path }}"
    owner: root
    group: root
  with_community.general.filetree: "{{ portage_etc_templates_dir }}"
  when: item.state == 'file'
  tags: portage_init

- name: copy env templates into /etc/portage
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/portage/{{ item.path }}"
    owner: root
    group: root
  with_community.general.filetree: "{{ portage_env_templates_dir }}"
  when: item.state == 'file'
  tags: portage_init

- name: create /etc/portage/savedconfig/sys-kernel/gentoo-kernel
  ansible.builtin.shell: zcat /proc/config.gz > /etc/portage/savedconfig/sys-kernel/gentoo-kernel
  when: portage_init_force is defined and portage_init_force | bool
  tags: portage_init
  
- name: install base packages
  community.general.portage:
    package: "{{ item }}"
    quiet: yes
    state: present
  loop: "{{ SYSPKGS }}"
  tags: system_install

- name: check if layman configured correctly
  ansible.builtin.lineinfile:
    path: /etc/layman/layman.cfg
    regexp: "^#?conf_type :"
    line: "conf_type : repos.conf"
    state: present
  tags: portage_init,layman_init,layman_conf,layman

- name: (Re)build layman.conf and create eix database
  block:
    - name: Rebuild /etc/portage/repos.conf/layman.conf
      ansible.builtin.command: layman-updater -R
      tags: portage_init,layman_init,layman

    - name: create eix database after install
      ansible.builtin.command: eix-update 
      tags: portage_init,eix_init,eix
  when: portage_init_force is defined and portage_init_force | bool
