---
# Upgrade system and install packages
- name: Install all packages
  community.general.portage:
    package: "{{ common_portage_packages }}"
    quiet: true
    state: present
  tags: common_install_packages,portage_install_packages
  when: install_packages_force is defined and install_packages_force | bool

- name: Update world
  community.general.portage:
    package: "@world"
    quiet: true
    deep: true
    newuse: true
    update: true
    sync: true
  tags: common_update_system,portage_update_system
  when: common_update_system is defined and common_update_system | bool
