---
# generate and put ssh-keys on cluster hosts
- name: Get user info and check if common_user_sk has executable shell
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.user:
    name: "{{ common_user_sk }}"
    state: "present"
    shell: "{{ common_user_sk_shell }}"
  register: user_info

- name: Check if ${HOME}/.ssh dir exists
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.file:
    path: "{{ user_info.home }}/.ssh"
    state: directory
    owner: "{{ common_user_sk }}"
    mode: "0700"

- name: Check if ssh-keys exist on target host
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.stat:
    path: "{{ user_info.home }}/.ssh/id_rsa"
  register: sk_exist_local

- name: Check if ssh-keys for host exist in central store
  tags: ssh_keys
  ansible.builtin.stat:
    path: "{{ common_central_store }}/{{ common_full_hostname }}-{{ common_user_sk }}-id_rsa"
  register: sk_exist_central

- name: Generate ssh-keys for user
  tags: ssh_keys
  when: not sk_exist_local.stat.exists and not sk_exist_central.stat.exists
  community.crypto.openssh_keypair:
    path: "/var/tmp/{{ common_full_hostname }}-{{ common_user_sk }}-id_rsa"
    size: 2048
    state: present
    type: rsa
    mode: "0600"
  delegate_to: 127.0.0.1

- name: Copy exist keys from central store
  when: not sk_exist_local.stat.exists and sk_exist_central.stat.exists
  tags: ssh_keys
  ansible.builtin.fetch:
    dest: "/var/tmp/"
    src: "{{ common_central_store }}/{{ common_full_hostname }}-{{ common_user_sk }}-{{ item }}"
    flat: true
    mode: "0600"
  loop:
    - "id_rsa"
    - "id_rsa.pub"

- name: Copy exist keys from target host to temp local dir
  become: true
  become_user: root
  when: sk_exist_local.stat.exists and not sk_exist_central.stat.exists
  tags: ssh_keys
  ansible.builtin.fetch:
    dest: "/var/tmp/{{ common_full_hostname }}-{{ common_user_sk }}-{{ item }}"
    src: "{{ user_info.home }}/.ssh/{{ item }}"
#    src: "
    flat: true
    mode: "0600"
  loop:
    - "id_rsa"
    - "id_rsa.pub"

- name: Copy ssh-keys to target hosts
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ user_info.home }}/.ssh/{{ item | basename | regex_replace(common_full_hostname + '-' + common_user_sk + '-', '') }}"
    owner: "{{ common_user_sk }}"
    mode: "0600"
  with_fileglob: '/var/tmp/{{ common_full_hostname }}-{{ common_user_sk }}-id_rsa*'

- name: Create authorized key for user
  become: true
  become_user: root
  tags: ssh_keys
  ansible.posix.authorized_key:
    user: "{{ common_user_sk }}"
    state: present
    key: "{{
      lookup('ansible.builtin.file',
        '/var/tmp/' +
        hostvars[item]['common_full_hostname'] +
        '-' +
        hostvars[item]['common_user_sk'] +
        '-id_rsa.pub')
    }}"
  loop: "{{ groups[common_sk_hosts_group] }}"

- name: Create known_hosts for user
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.known_hosts:
    hash_host: true
    path: "{{ user_info.home }}/.ssh/known_hosts"
    name: "{{ hostvars[item.0][item.1] }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + hostvars[item.0][item.1]) }}"
    state: present
  loop: "{{ groups[common_sk_hosts_group] | product(['common_ip4_default', 'common_full_hostname']) }}"

- name: Set owner group and mode for known_hosts file
  become: true
  become_user: root
  tags: ssh_keys
  ansible.builtin.file:
    path: "{{ user_info.home }}/.ssh/known_hosts"
    owner: "{{ common_user_sk }}"
    mode: "0600"

- name: Delete generated files
  tags: ssh_keys
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob: '/var/tmp/{{ common_full_hostname }}-{{ common_user_sk }}-id_rsa*'
  delegate_to: 127.0.0.1
