---
# Create ssl keys pair for objects
# Set pubkey_stat.stat.exists variable
- name: Get stats of a public key in central storage
  become: true
  become_user: root
  tags: create_ssl_keys
  ansible.builtin.stat:
    path: "{{ common_central_store }}/{{ common_ssl_cs_path }}/{{ csk.cert_filename }}"
  register: pubkey_stat
# Set key_info.valid_at.crit variable
- name: Get info for key from central storage
  become: true
  become_user: root
  when: pubkey_stat.stat.exists
  tags: create_ssl_keys
  community.crypto.x509_certificate_info:
    path: "{{ common_central_store }}/{{ common_ssl_cs_path }}/{{ csk.cert_filename }}"
    valid_at:
      crit: "+{{ csk.expired_period }}"
  register: key_info

# (Re)generate a pair of ssl keys: private and public
- name: Regenerate key pair if needed
  become: true
  become_user: root
  when: not pubkey_stat.stat.exists or not (key_info.valid_at.crit | default('true'))
  tags: create_ssl_keys
  block:
    - name: Generate private key
      delegate_to: "{{ csk.common_ssl_ca_host }}"
      community.crypto.openssl_privatekey:
        attributes: "{{ csk.attributes | default(omit) }}"
        backup: "{{ csk.privkey_backup | default(omit) }}"
        cipher: "{{ csk.cipher | default(omit) }}"
        curve: "{{ csk.curve | default(omit) }}"
        force: "{{ csk.force | default(omit) }}"
        format: "{{ csk.format | default(omit) }}"
        format_mismatch: "{{ csk.format_mismatch | default(omit) }}"
        group: "{{ csk.group | default('root') }}" 
        mode: "{{ csk.mode | default('0600') }}"
        owner: "{{ csk.owner | default('root') }}"
        passphrase: "{{ csk.passphrase | default(omit) }}"
        path: "{{ common_ssl_private_keys_dir }}/{{ csk.privatekey_filename }}"
        regenerate: "{{ csk.regenerate | default(omit) }}"
        return_content: true
        select_crypto_backend: "{{ csk.select_crypto_backend | default(omit) }}"
        selevel: "{{ csk.level | default(omit) }}"
        serole: "{{ csk.serole | default(omit) }}"
        setype: "{{ csk.setype | default(omit) }}"
        seuser: "{{ csk.seuser | default(omit) }}"
        size: "{{ csk.size | default(omit) }}"
        state: "{{ csk.state | default('present') }}"
        type: "{{ csk.type | default('RSA') }}"
        unsafe_writes: "{{ csk.unsafe_writes | default('false') }}"
      register: ssl_pk_var
    - name: Generate Certificate Signing Request on CA host
      delegate_to: "{{ csk.common_ssl_ca_host }}"
      community.crypto.openssl_csr:
        attributes: "{{ csk.attributes | default(omit) }}"
        authority_cert_issuer: "{{ csk.authority_cert_issuer | default(omit) }}"
        authority_cert_serial_number: "{{ csk.authority_cert_serial_number | default(omit) }}"
        authority_key_identifier: "{{ csk.authority_key_identifier | default(omit) }}"
        backup: "{{ csk.csr_backup | default(omit) }}"
        basic_constraints: "{{ csk.basic_constraints | default(omit) }}" # for example ['CA:TRUE']
        basic_constraints_critical: "{{ csk.basic_constraints_critical | default(omit) }}"
        common_name: "{{ csk.common_name }}"
        country_name: "{{ common_country_name | default(omit) }}"
        create_subject_key_identifier: "{{ csk.create_subject_key_identifier | default(omit) }}"
        crl_distribution_points: "{{ csk.crl_distribution_points | default(omit) }}"
        digest: "{{ csk.digest | default(omit) }}"
        email_address: "{{ csk.email_address | default(omit) }}"
        extended_key_usage: "{{ csk.extended_key_usage | default(omit) }}"
        extended_key_usage_critical: "{{ csk.extended_key_usage_critical | default(omit) }}"
        force: "{{ csk.force | default(omit) }}"
        group: "{{ csk.group | default('root') }}" 
        key_usage: "{{ csk.key_usage | default(omit) }}" # for example ['keyCertSign']
        key_usage_critical: "{{ csk.key_usage_critical | default(omit) }}"
        locality_name: "{{ csk.locality_name | default(omit) }}"
        mode: "{{ csk.mode | default('0600') }}"
        name_constraints_critical: "{{ csk.name_constraints_critical | default(omit) }}"
        name_constraints_excluded: "{{ csk.name_constraints_excluded | default(omit) }}"
        name_constraints_permitted: "{{ csk.name_constraints_permitted | default(omit) }}"
        ocsp_must_staple_critical: "{{ csk.ocsp_must_staple_critical | default(omit) }}"
        organization_name: "{{ common_organization_name | default(omit) }}"
        organizational_unit_name: "{{ csk.organizational_unit_name | default(omit) }}"
        owner: "{{ csk.owner | default('root') }}"
        path: "{{ common_ssl_private_keys_dir }}/{{ csk.csr_filename }}"
#        privatekey_content: "{{ ssl_pk_var.privatekey }}" # I use file, but you...
        privatekey_passphrase: "{{ csk.privatekey_passphrase | default(omit) }}"
        privatekey_path: "{{ common_ssl_private_keys_dir }}/{{ csk.privatekey_filename }}"
        return_content: true
        select_crypto_backend: "{{ csk.select_crypto_backend | default(omit) }}"
        selevel: "{{ csk.level | default(omit) }}"
        serole: "{{ csk.serole | default(omit) }}"
        setype: "{{ csk.setype | default(omit) }}"
        seuser: "{{ csk.seuser | default(omit) }}"
        state: "{{ csk.state | default('present') }}"
        state_or_province_name: "{{ csk.state_or_province_name | default(omit) }}"
        subject: "{{ csk.subject | default(omit) }}"
        subject_alt_name: "{{ csk.subject_alt_name | default(omit) }}"
        subject_alt_name_critical: "{{ csk.subject_alt_name_critical | default(omit) }}"
        subject_key_identifier: "{{ csk.subject_key_identifier | default(omit) }}"
        subject_ordered: "{{ csk.subject_ordered | default(omit) }}"
        unsafe_writes: "{{ csk.unsafe_writes | default('false') }}"
        use_common_name_for_san: "{{ csk.use_common_name_for_san | default(omit) }}"
        version: 1
      register: ssl_csr_var
    - name: Generate selfsigned cert
      delegate_to: "{{ csk.common_ssl_ca_host }}"
      community.crypto.x509_certificate:
        acme_accountkey_path: "{{ csk.acme_accountkey_path | default(omit) }}"
        acme_chain: "{{ csk.acme_chain | default(omit) }}"
        acme_challenge_path: "{{ csk.acme_challenge_path | default(omit) }}"
        acme_directory: "{{ csk.acme_directory | default(omit) }}"
        attributes: "{{ csk.attributes | default(omit) }}"
        backup: "{{ csk.backup | default(omit) }}"
        csr_content: "{{ ssl_csr_var.csr }}"
#        csr_path: "{{ common_ssl_private_keys_dir }}/{{ csk.csr_filename }}"
        force: "{{ csk.force | default(omit) }}"
        group: "{{ csk.group | default('root') }}" 
        ignore_timestamps: "{{ csk.ignore_timestamps | default(omit) }}"
        mode: "{{ csk.mode | default('0644') }}"
#        ownca_content: "{{ csk.ownca_content }}" # I use file, but you...
        ownca_create_authority_key_identifier: "{{ csk.ownca_create_authority_key_identifier | default(omit) }}"
        ownca_create_subject_key_identifier: "{{ csk.ownca_create_subject_key_identifier | default(omit) }}"
        ownca_digest: "{{ csk.ownca_digest | default(omit) }}"
        ownca_not_after: "{{ csk.ownca_not_after | default(omit) }}"
        ownca_not_before: "{{ csk.ownca_not_before | default(omit) }}"
        ownca_path: "{{ csk.ownca_path | default(omit) }}"
#        ownca_privatekey_content: "{{ csk.ownca_privatekey_content }}" # I use file, but you...
        ownca_privatekey_passphrase: "{{ csk.ownca_privatekey_passphrase | default(omit) }}"
        ownca_privatekey_path: "{{ csk.ownca_privatekey_path }}"
        ownca_version: "{{ csk.ownca_version | default(omit) }}"
        owner: "{{ csk.owner | default('root') }}"
        path: "{{ common_ssl_certs_dir }}/{{ csk.cert_filename }}"
#        privatekey_content: "{{ ssl_pk_var.privatekey }}" # I use file, but you...
        privatekey_passphrase: "{{ csk.privatekey_passphrase | default(omit) }}"
        privatekey_path: "{{ csk.privkey_fullpath | default(omit) }}"
        provider: "{{ csk.provider | default('ownca') }}"
        return_content: true
        select_crypto_backend: "{{ csk.select_crypto_backend | default(omit) }}"
        selevel: "{{ csk.level | default(omit) }}"
        selfsigned_create_subject_key_identifier: "{{ csk.selfsigned_create_subject_key_identifier | default(omit) }}"
        selfsigned_digest: "{{ csk.selfsigned_digest | default(omit) }}"
        selfsigned_not_after: "{{ csk.selfsigned_not_after | default(omit) }}"
        selfsigned_not_before: "{{ csk.selfsigned_not_before | default(omit) }}"
        selfsigned_version: "{{ csk.selfsigned_version | default(omit) }}"
        serole: "{{ csk.serole | default(omit) }}"
        setype: "{{ csk.setype | default(omit) }}"
        seuser: "{{ csk.seuser | default(omit) }}"
        state: "{{ csk.state | default('present') }}"
        unsafe_writes: "{{ csk.unsafe_writes | default('false') }}"
      register: ssl_cert_var
      notify: Upload ca
    - name: Copy SSL cert to central storage
      ansible.builtin.copy:
        dest: "{{ common_central_store }}/{{ common_ssl_cs_path }}/{{ csk.cert_filename }}"
        content: "{{ ssl_cert_var.certificate }}"
        mode: "0644"
      delegate_to: 127.0.0.1
    - name: Copy SSL private key to central storage
      ansible.builtin.copy:
        dest: "{{ common_central_store }}/{{ common_ssl_cs_path }}/{{ csk.privatekey_filename }}"
        content: "{{ ssl_pk_var.privatekey }}"
        mode: "0644"
      delegate_to: 127.0.0.1
