---

# handlers file for common
- name: rebuild locales
  community.general.locale_gen:
    name: "{{ item.locale }}"
    state: present
  loop: "{{ common_locales_list }}"

- name: timesync_service restart
  ansible.builtin.service:
    name: "{{ common_timesync_service }}"
    state: restarted

- name: resolver restart
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: distccd restart
  ansible.builtin.service:
    name: distccd
    state: restarted

- name: networkmanager restart
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
