---

# handlers file for common
- name: rebuild locales
  community.general.locale_gen:
    name: "{{ item.locale }}"
    state: present
  loop: "{{ common_locales_list }}"

- name: timesync_service restart
  ansible.builtin.service:
    name: "{{ common_timesync_service }}"
    state: restarted

- name: timesync_service enable
  ansible.builtin.service:
    name: "{{ common_timesync_service }}"
    enabled: true

- name: resolver restart
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: resolver enable
  ansible.builtin.service:
    name: systemd-resolved
    enabled: true

- name: systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: networkmanager restart
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: cron start
  ansible.builtin.service:
    name: "{{ common_cron_service }}"
    state: started

- name: cron enable
  ansible.builtin.service:
    name: "{{ common_cron_service }}"
    enabled: true
    
- name: upload ca
  ansible.builtin.shell:
    cmd: "{{ common_upload_ca }}"
  when: common_upload_ca is defined and common_upload_ca | length > 0
